#!/bin/bash

# Check key environments

if [ -z "$KHOME" ]; then
  echo "Please set KHOME first!"
  exit 1
fi
KSCRIPT_DIR="$KHOME/afl_integration/build_example"
echo "ls $KSCRIPT_DIR"
ls "$KSCRIPT_DIR"

if [ -z "$LDFLAGS" ]; then
  echo "Please put k-afl-llvm-rt into LDFLAGS first!"
  exit 1
else
  echo "LDFLAGS=$LDFLAGS"
fi

if [ -z "$CFLAGS" ] && [ -z "$CXXFLAGS" ]; then
  echo "Check CFLAGS and CXXFLAGS first!"
  exit 1
else
  echo "CFLAGS=$CFLAGS"
  echo "CXXFLAGS=$CXXFLAGS"
fi

# Parameter checking
if [ $# -lt 2 ]; then
  echo "<BUILD>: <SUBJECT_DIR> <BENCH_DIR>"
  exit 1
fi

# Get abspath to subject directory
SUBJECT_DIR="$1"
pushd "$SUBJECT_DIR" || exit 1
  SUBJECT_DIR="$PWD"
popd || exit 1

# Get abspath to target directory
BENCH_DIR="$2"
pushd "$BENCH_DIR" || exit 1
  BENCH_DIR="$PWD"
popd || exit 1

# Choose compilers
export CC=wllvm
export CXX=wllvm++

# Show configuration results
echo "==================== CONF-LOG ===================="
echo "SUBJECT_DIR=$SUBJECT_DIR"
echo "BENCH_DIR=$BENCH_DIR"
echo "CC=$CC"
echo "CXX=$CXX"
echo "==================== CONF-LOG ===================="
sleep 3

# Instrument SUBJECT programs
pushd "$SUBJECT_DIR" || exit 1
  # Build libs
  ./configure --disable-shared
  make clean
  make -j "$(nproc)"
  # Build readpng
  $CC -o readpng ./contrib/libtests/readpng.c ./.libs/libpng16.a -lz -lm
popd || exit 1

# Move to target directory
TARGET="readpng"
TARGET_DIR="$BENCH_DIR/$TARGET"
# Refresh
if [ -d "$TARGET_DIR" ]; then
  rm -rf "$TARGET_DIR"
fi
mkdir -p "$TARGET_DIR"
mv "$SUBJECT_DIR/$TARGET" "$TARGET_DIR"

# Extract cfgs. Modified on K-scheduler official scripts
pushd "$TARGET_DIR" || exit 1
  echo "extract-bc $TARGET"
  extract-bc "$TARGET"

  echo "llvm-dis $TARGET.bc"
  llvm-dis "$TARGET.bc"

  echo "python3 $KSCRIPT_DIR/fix_long_fun_name.py $TARGET.ll"
  python3 "$KSCRIPT_DIR/fix_long_fun_name.py" "$TARGET.ll"

  echo "mkdir cfg_out"
  mkdir cfg_out

  cd cfg_out || exit 1

  echo "opt -dot-cfg ../$TARGET.ll"
  opt -dot-cfg ../"$TARGET.ll"

  # The intra-CFGs generated by llvm opt are stored as hidden files, rename them as normal files.
  echo "Rename..."
  for f in $(ls -a |grep '^\.*'|grep dot);do mv $f ${f:1};done

  # Stitch intra-CFGs into a inter-CFG following caller-callee relationships
  cd .. || exit 1
  if [ -e katz ]; then
    rm -rf katz
    echo "Recreate $PWD/katz"
  fi
  mkdir katz
  cd katz || exit 1
  echo "python3 $KSCRIPT_DIR/gen_graph.py ../$TARGET.ll ../cfg_out"
  python3 "$KSCRIPT_DIR/gen_graph.py" "../$TARGET.ll" ../cfg_out
popd || exit
